package apiExploration;

public class Incident {

    private String short_description;  // Field to set in request
    private String caller_id;          // Field to set in request
    private String sys_id;             // Field returned in response
    private String number;             // Field returned in response

    // Constructor for POST request (without sys_id and number)
    public Incident(String short_description, String caller_id) {
        this.short_description = short_description;
        this.caller_id = caller_id;
    }

    // Getter and Setter for short_description
    public String getShort_description() {
        return short_description;
    }

    public void setShort_description(String short_description) {
        this.short_description = short_description;
    }

    // Getter and Setter for caller_id
    public String getCaller_id() {
        return caller_id;
    }

    public void setCaller_id(String caller_id) {
        this.caller_id = caller_id;
    }

    // Getter for sys_id (no setter, as this is generated by ServiceNow)
    public String getSys_id() {
        return sys_id;
    }

    // Getter for number (no setter, as this is generated by ServiceNow)
    public String getNumber() {
        return number;
    }
}
